export default {
  dark: {
    primary: '#243447',
    primaryLight: '#F5F5F5',
    primaryDark: '#141d26',
    accent: '#1BA1F1',
    transparentDark: 'rgba(0,0,0,0.5)',
    divider: '#37474f',
    hint: '#bdbdbd',
    contrast: '#FFF',
    statusBarColor: '#141d26',
    barStyle: 'light-content',
  },
  light: {
    primary: '#FFFFFF',
    primaryLight: '#F5F5F5',
    primaryDark: '#E6ECF0',
    accent: '#1BA1F1',
    transparentDark: 'rgba(0,0,0,0.5)',
    divider: '#E6ECF0',
    hint: 'gray',
    contrast: '#000000',
    statusBarColor: '#F5F5F5',
    barStyle: 'dark-content',
  },
};
